VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

MOUSEKEY_ENABLE = no
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = no
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes
